kitchen_managment/urls.py
from django.urls import path
from kitchen_managment.views import (
    index,
    CookCreateView,
    CookDetailView,
    CookExperienceUpdateView,
    CookListView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    ToggleAssignToDishView,
)

urlpatterns = [
    path("", index, name="index",),
    path("dishtype/", DishTypeListView.as_view(), name="dishtype-list",),
    path(
        "dishtype/create/",
        DishTypeCreateView.as_view(),
        name="dishtype-create",),
    path(
        "dishtype/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dishtype-update",),
    path(
        "dishtype/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dishtype-delete"),
    path("dish/", DishListView.as_view(), name="dish-list",),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail",),
    path("dish/create/", DishCreateView.as_view(), name="dish-create",),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update",),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete",),
    path(
       "dish/<int:pk>/toggle-assign/",
       ToggleAssignToDishView.as_view(),
       name="toggle-dish-assign",
    ),
    path("cook/", CookListView.as_view(), name="cook-list",),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cook/create/", CookCreateView.as_view(), name="cook-create",),
    path(
        "cook/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="cook-update",),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "kitchen_managment"

kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen_managment.urls", namespace="kitchen_managment")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">Prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
{% load static %}
<nav class="navbar navbar-expand-lg custom_nav-container pt-3">
  <a
    class="navbar-brand"
    href="{% url 'kitchen_managment:index' %}"
  >
    <img
      src="{% static 'images/logo.png' %}"
      alt=""
    >
    <span>
      Kitchen Managment
    </span>
  </a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div
    class="collapse navbar-collapse"
    id="navbarSupportedContent"
  >
    <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
      <ul class="navbar-nav  ">
        <li class="nav-item active">
          <a
            class="nav-link"
            href="{% url 'kitchen_managment:index' %}"
          >
            Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'kitchen_managment:dish-list' %}"
          > Dishes</a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'kitchen_managment:dishtype-list' %}"
          > Dish Types</a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'kitchen_managment:cook-list' %}"
          >Cooks</a>
        </li>
      </ul>
    </div>
    <div class="quote_btn-container ml-0 ml-lg-4 d-flex justify-content-center">
      {% if user.is_authenticated %}
      <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a>
      <a href="{% url 'logout' %}?next={{request.path}}">Logout</a>
      {% else %}
      <a href="{% url 'login' %}?next={{request.path}}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>