kitchen_managment/urls.py
from django.urls import path
from kitchen_managment.views import (
    index,
    CookCreateView,
    CookDetailView,
    CookExperienceUpdateView,
    CookListView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    ToggleAssignToDishView,
)

urlpatterns = [
    path("", index, name="index",),
    path("dishtype/", DishTypeListView.as_view(), name="dishtype-list",),
    path(
        "dishtype/create/",
        DishTypeCreateView.as_view(),
        name="dishtype-create",),
    path(
        "dishtype/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dishtype-update",),
    path(
        "dishtype/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dishtype-delete"),
    path("dish/", DishListView.as_view(), name="dish-list",),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail",),
    path("dish/create/", DishCreateView.as_view(), name="dish-create",),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update",),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete",),
    path(
       "dish/<int:pk>/toggle-assign/",
       ToggleAssignToDishView.as_view(),
       name="toggle-dish-assign",
    ),
    path("cook/", CookListView.as_view(), name="cook-list",),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cook/create/", CookCreateView.as_view(), name="cook-create",),
    path(
        "cook/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="cook-update",),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "kitchen_managment"

kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen_managment.urls", namespace="kitchen_managment")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen_managment/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)
    
    
    class Meta:
        ordering = ["name"]
    
    def __str__(self) -> str:
        return f"{self.name}"


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)
    
    
    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"
    
    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen_managment:cook-detail",
                       kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dishtype = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook,
                                   related_name="dishes",
                                   blank=True)
    
    
    class Meta:
        ordering = ["name"]
    
    def __str__(self) -> str:
        return f"{self.name} {self.price}"

kitchen_managment/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from kitchen_managment.models import Dish, Cook
from django.core.validators import MaxValueValidator, MinValueValidator


class CookCreationForm(UserCreationForm):
    years_of_experience = forms.IntegerField(
        required=True,
        validators=[MinValueValidator(0), MaxValueValidator(50)]
    )
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + ("first_name",
                                                 "last_name",
                                                 "years_of_experience",
                                                 "email")


class CookExperienceUpdateForm(forms.ModelForm):
    years_of_experience = forms.IntegerField(
        required=True,
        validators=[MinValueValidator(0), MaxValueValidator(50)]
    )
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = ("years_of_experience",
                  "first_name",
                  "last_name",)


class CookUsernameSearchForm(forms.Form):
    username = forms.CharField(max_length=150,
                               required=False,
                               label="",
                               widget=forms.TextInput(
                                   attrs={"placeholder": "Search by username"}
                               )
                               )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=Cook.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishNameSearchForm(forms.Form):
    name = forms.CharField(max_length=255,
                           required=False,
                           label="",
                           widget=forms.TextInput(
                               attrs={"placeholder": "Search by name"}
                               )
                           )


class DishTypeNameSearchForm(forms.Form):
    name = forms.CharField(max_length=255,
                           required=False,
                           label="",
                           widget=forms.TextInput(
                               attrs={"placeholder": "Search by name"}
                            )
                           )

kitchen_managment/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from kitchen_managment.forms import (CookCreationForm,
                                     CookExperienceUpdateForm,
                                     CookUsernameSearchForm,
                                     DishForm,
                                     DishNameSearchForm,
                                     DishTypeNameSearchForm)
from kitchen_managment.models import Dish, DishType, Cook


def index(request):
    num_cooks = Cook.objects.count()
    num_dish = Dish.objects.count()
    num_dishtype = DishType.objects.count()
    
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    
    context = {
        "num_cooks": num_cooks,
        "num_dish": num_dish,
        "num_dishtype": num_dishtype,
        "num_visits": num_visits + 1,
    }
    
    return render(request, "kitchen_managment/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dishtype_list"
    template_name = "kitchen_managment/dishtype_list.html"
    paginate_by = 10
    queryset = DishType.objects.all()
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "",)
        context["search_form"] = DishTypeNameSearchForm(
            initial={"name": name})
        return context

    def get_queryset(self):
        form = DishTypeNameSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"])


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen_managment:dishtype-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen_managment:dishtype-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen_managment:dishtype-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 10
    queryset = Dish.objects.all().select_related("dishtype")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishNameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        form = DishNameSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"])


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    
    def toggle_assign_to_dish(request, pk):
        cook = Cook.objects.get(id=request.user.id)
        if (Dish.objects.get(id=pk) in cook.dishes.all()):
            cook.dishes.remove(pk)
        else:
            cook.dishes.add(pk)
        return HttpResponseRedirect(reverse_lazy("kitchen_managment:dish-detail", args=[pk]))

class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    success_url = reverse_lazy("kitchen_managment:dish-list")
    form_class = DishForm


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    success_url = reverse_lazy("kitchen_managment:dish-list")
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen_managment:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 10
    queryset = Cook.objects.all()
    
    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookUsernameSearchForm(
            initial={"username": username}
        )
        return context
    
    def get_queryset(self):
        form = CookUsernameSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            ) 


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("dishes__dishtype")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    template_name = "kitchen_managment/cook_create.html"
    success_url = reverse_lazy("kitchen_managment:cook-list")


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    template_name = "kitchen_managment/cook_update.html"
    success_url = reverse_lazy("kitchen_managment:cook-list")
    form_class = CookExperienceUpdateForm


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen_managment:cook-list")


class ToggleAssignToDishView(LoginRequiredMixin, generic.View):
    @staticmethod
    def post(request, pk):
        cook = Cook.objects.get(id=request.user.id)
        if (Dish.objects.get(id=pk) in cook.dishes.all()):
            cook.dishes.remove(pk)
        else:
            cook.dishes.add(pk)
        return HttpResponseRedirect(
            reverse_lazy("kitchen_managment:dish-detail",
                                                 args=[pk]))

templates/kitchen_managment/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete cook?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen_managment/cook_create.html
{% extends "base.html" %}

{% block content %}
<section class="contact_section layout_padding">
  <div class="container">
    <h1>Create cook</h1>
    <div class="row">
      <div class="col-md-8 mr-auto">
        <form
          action=""
          method="post"
          novalidate
        >
          {% csrf_token %}
          <div>
            <p>Username</p>
            {{ form.username }}
          </div>
          <span class="errors">{{ form.username.errors }}</span>
          <div>
            <p>First name</p>
            {{ form.first_name }}
          </div>
          <div>
            <p>Last name</p>
            {{ form.last_name }}
          </div>
          <div>
            <p>Email</p>  
            {{ form.email }}
          </div>
          <span class="errors">{{ form.email.errors }}</span>
          <div>
            <p>Years of experience</p>
            {{ form.years_of_experience }}
          </div>
          <div>
            <p>Password</p>
            {{ form.password1}}
          </div>
          <span class="errors">{{ form.password1.errors }}</span>
          <div>
            <p>Repeat password</p>
            {{ form.password2 }}
          </div>
          <span class="errors">{{ form.password2.errors }}</span>
          <div class="mt-5">
            <input
              type="submit"
              value="Submit"
              class="btn btn-primary"
            >
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/kitchen_managment/cook_detail.html
{% extends "base.html" %}

{% block content %}
<section class="fruit_section layout_padding-top">
  <div class="container">
    <div class="row layout_padding2">
      <div class="col-md-8">
        <div class="fruit_detail-box">
          <h3>
            Username: {{ cook.username }}
          </h3>
          <p class="mt-4 mb-5">
            <p><strong>First name:</strong> {{ cook.first_name }}</p>
            <p><strong>Last name:</strong> {{ cook.last_name }}</p>
            <p><strong>Years of experience:</strong> {{ cook.license_number }}</p>
            <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>
          </p>
          <div>
            <a href="{% url 'kitchen_managment:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
              Delete
            </a>
            <a href="{% url 'kitchen_managment:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
              Update
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  {% endblock %}

templates/kitchen_managment/cook_list.html
{% extends "base.html" %}

{% block content %}
<section class="">
  <div class="search_form layout_padding-bottom">
    <form
      action=""
      method="get"
      class="search_form_txt"
    >
      {{ search_form }}
      <input
        type="submit"
        class="search_form_btn"
        value="Search"
      >
    </form>
  </div>
  {% if cook_list %}
  <br>
  <table class="table">
    <tr>
      <th>ID</th>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Years of experience</th>
    </tr>
    {% for cook in cook_list %}
    <tr>
      <td>{{ cook.id }}</td>
      <td>
        <a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a>
      </td>
      <td>{{ cook.first_name }}</td>
      <td>{{ cook.last_name }}</td>
      <td>{{ cook.years_of_experience }}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>There are no cooks in the service.</p>
  {% endif %}
  <a
    href="{% url 'kitchen_managment:cook-create' %}"
    class="btn btn-primary link-to-page"
  >
    Create
  </a>
</section>
{% endblock %}

templates/kitchen_managment/cook_update.html
{% extends "base.html" %}

{% block content %}
  <h1>Update years of experience</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen_managment/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen_managment/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ dish.name }}
    <a href="{% url 'kitchen_managment:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen_managment:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p>DishType: {{ dish.dishtype.name }}</p>
  <p>Description: {{ dish.description }}</p>
  <h1>
    Cooks
    {% if dish in user.dish.all %}
      <a href="{% url 'kitchen_managment:toggle-dish-assign' pk=dish.id %}" class="btn btn-danger link-to-page">
        Delete me from this dish
      </a>
    {% else %}
      <a href="{% url 'kitchen_managment:toggle-dish-assign' pk=dish.id %}" class="btn btn-success link-to-page">
        Assign me from this dish
      </a>
    {% endif %}
  </h1>
  <hr>
  <ul>
    {% for cook in dish.cooks.all %}
      <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/kitchen_managment/dish_form.html
{% extends "base.html" %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen_managment/dish_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="service_section">
  <div class="search_form layout_padding" style="padding-left: 550px;">
    <form
      action=""
      method="get"
      class="form-inline"
    >
      {{ search_form }}
      <input
        type="submit"
        class="btn btn-primary"
        value="Search"
      >
    </form>
  </div>
  <div class="container">
    <div class="">
      {% if dish_list %}
      <div class="card-deck">
        {% for dish in dish_list %}
        <a
          href="{% url 'kitchen_managment:dish-detail' pk=dish.id %}"
          class="card"
        >
          <img
            class="card-img-top"
            src="{% static 'images/card-item-3.png' %}"
            alt="Card image cap"
          >
          <div class="card-body">
            <h5
              class="card-title"
            >
              {{ dish.name }}
            </h5>
            <p class="card-text">
              {{ dish.description}}
            </p>
            <br>
            <p class="card-text">
                {{ dish.price }}
            </p>
          </div>
        </a>
        {% endfor %}
      </div>
      {% else %}
      <p>The list is empty, you dont add dishes</p>
      {% endif %}
      <a
        href="{% url 'kitchen_managment:dish-create' %}"
        class="btn btn-primary link-to-page"
      >
        Create
      </a>
    </div>
  </div>
</section>
{% endblock %}

templates/kitchen_managment/dishtype_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dishtype?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen_managment/dishtype_form.html
{% extends "base.html" %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dishtype</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen_managment/dishtype_list.html
{% extends "base.html" %}

{% block content %}
<section class="">
  <div class="search_form layout_padding-bottom">
    <form
      action=""
      method="get"
      class="search_form_txt"
    >
      {{ search_form }}
      <input
        type="submit"
        class="search_form_btn"
        value="Search"
      >
    </form>
  </div>    
  {% if dishtype_list %}
  <br>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for dishtype in dishtype_list %}
    <tr>
      <td>{{ dishtype.name }}</td>
      <td>
        <a href="{% url 'kitchen_managment:dishtype-update' pk=dishtype.id %}">
          Update
        </a>
      </td>
      <td>
        <a
          style="color: darkorange"
          href="{% url 'kitchen_managment:dishtype-delete' pk=dishtype.id %}"
        >
          Delete
        </a>
      </td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>There are no dishtypes in the service.</p>
  {% endif %}
  <a
    href="{% url 'kitchen_managment:dishtype-create' %}"
    class="btn btn-primary link-to-page"
  >
    Create
  </a>
</section>
{% endblock %}

templates/kitchen_managment/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="service_section layout_padding ">
  <div class="container">
    <div class=" layout_padding2">
      <div class="card-deck">
        <a
        href="{% url 'kitchen_managment:cook-list' %}"
        class="card">
          <img
            class="card-img-top"
            src="{% static 'images/card-item-1.png' %}"
            alt="Card image cap"
          >
          <div class="card-body">
            <h5 class="card-title">Cooks</h5>
            <p class="card-text">
              Currently, there are {{ num_cooks }} cooks working in our
              kitchen who will make your dishes exceptionally delicious and exquisite.
            </p>
          </div>
        </a>
        <a
        href="{% url 'kitchen_managment:dish-list' %}"
        class="card">
          <img
            class="card-img-top"
            src="{% static 'images/card-item-2.png' %}"
            alt="Card image cap"
          >
          <div class="card-body">
            <h5 class="card-title">Dishes</h5>
            <p class="card-text">
                Currently, our menu features {{ num_dish }} dishes, each of which
                is a masterpiece that will please the taste of anyone.
            </p>
          </div>
        </a>
        <a
        href="{% url 'kitchen_managment:dishtype-list' %}"
        class="card">
          <img
            class="card-img-top"
            src="{% static 'images/card-item-3.png' %}"
            alt="Card image cap"
          >
          <div class="card-body">
            <h5 class="card-title">Dish Types</h5>
            <p class="card-text">
                Currently, our restaurant offers {{ num_dishtype }} types of dishes, but we are not standing still and are ready to grow.
            </p>
          </div>
        </a>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
      </p>
    </div>
  </div>
</section>
{% endblock %}